name: Manually Deploy to heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: akhileshns/heroku-deploy@v3.14.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          region: "eu"
          usedocker: true
          docker_heroku_process_type: worker
        env:
          HD_TELE_TOKEN: ${{secrets.TELE_TOKEN}}
          HD_DEV_TELE_ID: ${{secrets.DEV_TELE_ID}}
          HD_GOOGLE_APPLICATION_CREDENTIALS: ${{secrets.GOOGLE_APPLICATION_CREDENTIALS}}
